# Generated by Django 4.1.3 on 2022-11-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0002_person_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='species',
        ),
    ]
