# Generated by Django 4.1.3 on 2022-11-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0003_remove_person_species'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Species',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='person',
            name='eye_color',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
