# Generated by Django 4.1.3 on 2022-11-04 14:46

from django.db import migrations, models
import my_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0004_delete_species_remove_person_birth_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
